apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: hello-redis-app
spec:
  selector:
    matchLabels:
      app: hello-redis-app
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-redis-app
    spec:
      containers:
        - name: redis
          image: redis
        - name: hello-redis
          image: erhangundogan/hello-redis:1.1.2
          imagePullPolicy: IfNotPresent

